---
- name: Install Docker on all hosts
  hosts: all
  become: true  # Use sudo for administrative tasks
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600  # Update cache every hour

    - name: Install prerequisites for Docker
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker's official GPG key
      command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      register: result
      ignore_errors: yes

    - name: Add Docker repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable'
        state: present

    - name: Install Docker CE (Community Edition)
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker service is started and enabled
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        group: docker
        append: yes
        state: present
