name: Terraform plan / apply

on:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
  workflow_dispatch: 
    inputs:
      environment:
        type: choice
        description: Envornment
        options: 
        - dev
        - stage
        - prod
        - all
        default: test
  

jobs:

  build:
    env: 
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    
    - name: Terraform Format
      run: terraform fmt -check

    - name: Terraform plan 
      run: |
        cd 27
        az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}
        terraform init
        if [[ "${{ github.event.inputs.environment }}" == "all" ]]; then
            terraform plan 
        else
            terraform workspace select ${{ github.event.inputs.environment }}
            terraform plan -var "public_key=${{ secrets.PUBLIC_KEY }}" -var-file vars.${{ github.event.inputs.environment }}.tfvars -out ${{ github.event.inputs.environment }}.plan
        fi
    - name: Terraform apply
      run: |
        cd 27
        if [[ "${{ github.event.inputs.environment }}" == "all" ]]; then
            terraform apply --auto-apprrove
        else
            terraform workspace select ${{ github.event.inputs.environment }}
            terraform apply --auto-approve "${{ github.event.inputs.environment }}.plan"
        fi
